// Code generated by goctl. DO NOT EDIT!
// Source: echo.proto

package echo

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	Request struct {
		Msg string `json:"msg,omitempty"`
	}

	Response struct {
		Msg string `json:"msg,omitempty"`
	}
)
