// Code generated by goctl. DO NOT EDIT!
// Source: echo.proto

package server

import (
	"context"

	"github.com/just-coding-0/learn_example/micro_service/zero/rpc/echo/internal/logic"
	"github.com/just-coding-0/learn_example/micro_service/zero/rpc/echo/internal/svc"
	echo "github.com/just-coding-0/learn_example/micro_service/zero/rpc/echo/pb"
)

type EchoServer struct {
	svcCtx *svc.ServiceContext
}

func NewEchoServer(svcCtx *svc.ServiceContext) *EchoServer {
	return &EchoServer{
		svcCtx: svcCtx,
	}
}

func (s *EchoServer) Echo(ctx context.Context, in *echo.Request) (*echo.Response, error) {
	l := logic.NewEchoLogic(ctx, s.svcCtx)
	return l.Echo(in)
}
