// Code generated by goctl. DO NOT EDIT!
// Source: history.proto

package main

import (
	"flag"
	"fmt"

	"github.com/just-coding-0/learn_example/micro_service/echo/rpc/history/internal/config"
	"github.com/just-coding-0/learn_example/micro_service/echo/rpc/history/internal/server"
	"github.com/just-coding-0/learn_example/micro_service/echo/rpc/history/internal/svc"
	history "github.com/just-coding-0/learn_example/micro_service/echo/rpc/history/pb"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/core/logx"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/history.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	historySrv := server.NewHistoryServer(ctx)

	s, err := zrpc.NewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		history.RegisterHistoryServer(grpcServer, historySrv)
	})
	logx.Must(err)

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
