// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history.proto

package history

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AddResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LastRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastRequest) Reset()         { *m = LastRequest{} }
func (m *LastRequest) String() string { return proto.CompactTextString(m) }
func (*LastRequest) ProtoMessage()    {}
func (*LastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{2}
}

func (m *LastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastRequest.Unmarshal(m, b)
}
func (m *LastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastRequest.Marshal(b, m, deterministic)
}
func (m *LastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastRequest.Merge(m, src)
}
func (m *LastRequest) XXX_Size() int {
	return xxx_messageInfo_LastRequest.Size(m)
}
func (m *LastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastRequest proto.InternalMessageInfo

type LastResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Times                uint64   `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	LastEcho             string   `protobuf:"bytes,3,opt,name=lastEcho,proto3" json:"lastEcho,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastResponse) Reset()         { *m = LastResponse{} }
func (m *LastResponse) String() string { return proto.CompactTextString(m) }
func (*LastResponse) ProtoMessage()    {}
func (*LastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{3}
}

func (m *LastResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastResponse.Unmarshal(m, b)
}
func (m *LastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastResponse.Marshal(b, m, deterministic)
}
func (m *LastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastResponse.Merge(m, src)
}
func (m *LastResponse) XXX_Size() int {
	return xxx_messageInfo_LastResponse.Size(m)
}
func (m *LastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastResponse proto.InternalMessageInfo

func (m *LastResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LastResponse) GetTimes() uint64 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *LastResponse) GetLastEcho() string {
	if m != nil {
		return m.LastEcho
	}
	return ""
}

type GetRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Times                uint64   `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	LastEcho             string   `protobuf:"bytes,3,opt,name=lastEcho,proto3" json:"lastEcho,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetResponse) GetTimes() uint64 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *GetResponse) GetLastEcho() string {
	if m != nil {
		return m.LastEcho
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "history.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "history.AddResponse")
	proto.RegisterType((*LastRequest)(nil), "history.LastRequest")
	proto.RegisterType((*LastResponse)(nil), "history.LastResponse")
	proto.RegisterType((*GetRequest)(nil), "history.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "history.GetResponse")
}

func init() {
	proto.RegisterFile("history.proto", fileDescriptor_454388b49b309873)
}

var fileDescriptor_454388b49b309873 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc8, 0x2c, 0x2e,
	0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb8,
	0xb8, 0x1c, 0x53, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x73,
	0x8b, 0xd3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x59, 0x2e, 0x6e, 0xb0,
	0x7c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x10, 0x1f, 0x17, 0x53, 0x7e, 0x36, 0x58, 0x9e, 0x23,
	0x88, 0x29, 0x3f, 0x5b, 0x89, 0x97, 0x8b, 0xdb, 0x27, 0xb1, 0xb8, 0x04, 0xaa, 0x5f, 0x29, 0x88,
	0x8b, 0x07, 0xc2, 0x85, 0x2a, 0xc7, 0x30, 0x4f, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x33, 0x37, 0xb5,
	0x58, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0xc2, 0x11, 0x92, 0xe2, 0xe2, 0xc8, 0x49, 0x2c,
	0x2e, 0x71, 0x4d, 0xce, 0xc8, 0x97, 0x60, 0x06, 0x2b, 0x86, 0xf3, 0x41, 0x2e, 0x74, 0x4f, 0x2d,
	0xc1, 0xed, 0xc2, 0x40, 0x2e, 0x6e, 0xb0, 0x3c, 0xf5, 0xac, 0x34, 0x5a, 0xc4, 0xc8, 0xc5, 0xee,
	0x01, 0x09, 0x20, 0x21, 0x03, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x61, 0x3d, 0x58, 0x00, 0x22,
	0x82, 0x4b, 0x4a, 0x04, 0x55, 0x10, 0xea, 0x02, 0x63, 0x2e, 0x16, 0x50, 0x20, 0x08, 0x21, 0x64,
	0x91, 0x82, 0x48, 0x4a, 0x14, 0x4d, 0x14, 0xaa, 0xc9, 0x80, 0x8b, 0xd9, 0x3d, 0xb5, 0x04, 0xc9,
	0x1a, 0x84, 0x9f, 0x91, 0xac, 0x41, 0xf2, 0x68, 0x12, 0x1b, 0x38, 0x26, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x67, 0x28, 0x86, 0xb6, 0xda, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Last(ctx context.Context, in *LastRequest, opts ...grpc.CallOption) (*LastResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type historyClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryClient(cc grpc.ClientConnInterface) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/history.History/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) Last(ctx context.Context, in *LastRequest, opts ...grpc.CallOption) (*LastResponse, error) {
	out := new(LastResponse)
	err := c.cc.Invoke(ctx, "/history.History/Last", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/history.History/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
type HistoryServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Last(context.Context, *LastRequest) (*LastResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

// UnimplementedHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (*UnimplementedHistoryServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedHistoryServer) Last(ctx context.Context, req *LastRequest) (*LastResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Last not implemented")
}
func (*UnimplementedHistoryServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterHistoryServer(s *grpc.Server, srv HistoryServer) {
	s.RegisterService(&_History_serviceDesc, srv)
}

func _History_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_Last_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Last(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/Last",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Last(ctx, req.(*LastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _History_serviceDesc = grpc.ServiceDesc{
	ServiceName: "history.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _History_Add_Handler,
		},
		{
			MethodName: "Last",
			Handler:    _History_Last_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _History_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
