// Code generated by goctl. DO NOT EDIT.
package types

type EchoRequest struct {
	Msg string `form:"msg"`
}

type EchoResponse struct {
	Msg string `json:"msg"`
}

type GetEchoStatsRequest struct {
	Msg string `form:"msg"`
}

type GetEchoStatsResponse struct {
	Msg      string `json:"msg"`
	LastEcho string `json:"last_echo"`
	Times    uint64 `json:"times"`
}

type LastEchoResponse struct {
	Msg      string `json:"msg"`
	LastEcho string `json:"last_echo"`
	Times    uint64 `json:"times"`
}
