// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history.proto

package history

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AddResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type LastRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastRequest) Reset()         { *m = LastRequest{} }
func (m *LastRequest) String() string { return proto.CompactTextString(m) }
func (*LastRequest) ProtoMessage()    {}
func (*LastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{2}
}

func (m *LastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastRequest.Unmarshal(m, b)
}
func (m *LastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastRequest.Marshal(b, m, deterministic)
}
func (m *LastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastRequest.Merge(m, src)
}
func (m *LastRequest) XXX_Size() int {
	return xxx_messageInfo_LastRequest.Size(m)
}
func (m *LastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastRequest proto.InternalMessageInfo

type LastRequestResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Times                uint64   `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	LastEcho             string   `protobuf:"bytes,3,opt,name=lastEcho,proto3" json:"lastEcho,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastRequestResponse) Reset()         { *m = LastRequestResponse{} }
func (m *LastRequestResponse) String() string { return proto.CompactTextString(m) }
func (*LastRequestResponse) ProtoMessage()    {}
func (*LastRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_454388b49b309873, []int{3}
}

func (m *LastRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastRequestResponse.Unmarshal(m, b)
}
func (m *LastRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastRequestResponse.Marshal(b, m, deterministic)
}
func (m *LastRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastRequestResponse.Merge(m, src)
}
func (m *LastRequestResponse) XXX_Size() int {
	return xxx_messageInfo_LastRequestResponse.Size(m)
}
func (m *LastRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastRequestResponse proto.InternalMessageInfo

func (m *LastRequestResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LastRequestResponse) GetTimes() uint64 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *LastRequestResponse) GetLastEcho() string {
	if m != nil {
		return m.LastEcho
	}
	return ""
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "history.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "history.AddResponse")
	proto.RegisterType((*LastRequest)(nil), "history.LastRequest")
	proto.RegisterType((*LastRequestResponse)(nil), "history.LastRequestResponse")
}

func init() {
	proto.RegisterFile("history.proto", fileDescriptor_454388b49b309873)
}

var fileDescriptor_454388b49b309873 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc8, 0x2c, 0x2e,
	0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb8,
	0xb8, 0x1c, 0x53, 0x52, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0x73,
	0x8b, 0xd3, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x59, 0x2e, 0x6e, 0xb0,
	0x7c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x10, 0x1f, 0x17, 0x53, 0x7e, 0x36, 0x58, 0x9e, 0x23,
	0x88, 0x29, 0x3f, 0x5b, 0x89, 0x97, 0x8b, 0xdb, 0x27, 0xb1, 0xb8, 0x04, 0xaa, 0x5f, 0x29, 0x92,
	0x4b, 0x18, 0x89, 0x0b, 0xd7, 0x85, 0x61, 0xac, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x66, 0x6e, 0x6a,
	0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x84, 0x23, 0x24, 0xc5, 0xc5, 0x91, 0x93, 0x58,
	0x5c, 0xe2, 0x9a, 0x9c, 0x91, 0x2f, 0xc1, 0x0c, 0x56, 0x0c, 0xe7, 0x1b, 0x95, 0x73, 0xb1, 0x7b,
	0x40, 0xdc, 0x2c, 0x64, 0xc0, 0xc5, 0xec, 0x98, 0x92, 0x22, 0x24, 0xac, 0x07, 0xf3, 0x13, 0xc2,
	0x07, 0x52, 0x22, 0xa8, 0x82, 0x50, 0x07, 0x58, 0x71, 0xb1, 0x80, 0xdc, 0x25, 0x84, 0x90, 0x45,
	0x72, 0xa6, 0x94, 0x0c, 0x36, 0x51, 0x98, 0xde, 0x24, 0x36, 0x70, 0x88, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x24, 0x0b, 0xbd, 0x36, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Last(ctx context.Context, in *LastRequest, opts ...grpc.CallOption) (*LastRequestResponse, error)
}

type historyClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryClient(cc grpc.ClientConnInterface) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/history.History/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) Last(ctx context.Context, in *LastRequest, opts ...grpc.CallOption) (*LastRequestResponse, error) {
	out := new(LastRequestResponse)
	err := c.cc.Invoke(ctx, "/history.History/Last", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
type HistoryServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Last(context.Context, *LastRequest) (*LastRequestResponse, error)
}

// UnimplementedHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (*UnimplementedHistoryServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedHistoryServer) Last(ctx context.Context, req *LastRequest) (*LastRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Last not implemented")
}

func RegisterHistoryServer(s *grpc.Server, srv HistoryServer) {
	s.RegisterService(&_History_serviceDesc, srv)
}

func _History_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_Last_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).Last(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/Last",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).Last(ctx, req.(*LastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _History_serviceDesc = grpc.ServiceDesc{
	ServiceName: "history.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _History_Add_Handler,
		},
		{
			MethodName: "Last",
			Handler:    _History_Last_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
