// Code generated by goctl. DO NOT EDIT!
// Source: history.proto

package history

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	AddRequest struct {
		Msg string `json:"msg,omitempty"`
	}

	AddResponse struct {
		Ok bool `json:"ok,omitempty"`
	}

	GetRequest struct {
		Msg string `json:"msg,omitempty"`
	}

	GetResponse struct {
		Msg      string `json:"msg,omitempty"`
		Times    uint64 `json:"times,omitempty"`
		LastEcho string `json:"lastEcho,omitempty"`
	}

	LastRequest struct {
	}

	LastResponse struct {
		Msg      string `json:"msg,omitempty"`
		Times    uint64 `json:"times,omitempty"`
		LastEcho string `json:"lastEcho,omitempty"`
	}
)
