// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/just-coding-0/learn_example/micro_service/zero/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/echo",
			Handler: echoHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/last_echo",
			Handler: lastEchoHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/echo/stats",
			Handler: getEchoHandler(serverCtx),
		},
	})
}
