// Code generated by goctl. DO NOT EDIT.
package types

type EchoRequest struct {
	Msg string `from:"msg"`
}

type EchoResponse struct {
	Msg string `json:"msg"`
}

type LastEchoResponse struct {
	LastEcho string `json:"last_echo"`
	Word     string `json:"word"`
	Times    uint64 `json:"times"`
}
